create database Project_0;
use project_0;
create table Users(user_id int not null auto_increment, firstname varchar(30) NOT NULL, lastname varchar(30) NOT NULL, last_movie varchar(50) NOT NULL, primary key(user_id));
INSERT INTO users(firstname, lastname, last_movie) values
('Robert', 'Hill', 'Die Hard'),('Sarah', 'Parker', 'Pacific Rim'),('William', 'Williamson', 'Demon Slayer'),('Lauryn', 'Hill', 'Disturbia'),('Sebastion', 'Song', 'Beetlejuice'),('Margaret', 'Boothe', 'Terminator'),('Veronica', 'Jones', 'Spawn'),('Mordecai', 'Byrd', 'Nightmare On Elm Street'),('Alphonse', 'Elric', 'Romeo and Juliet'),('Geoff', 'Dunham', 'Zombieland'),
('David', 'Tenant', 'Love Actually'),('Peter', 'Parker', 'Spiderman'),('Robeert', 'Robertson', 'Velocipastor'),('Sampson', 'Shelby', 'Die Hard'),('James', 'Smith', 'BeetleJuice'),('Bobby', 'Hill', 'Jurassic Park'),('Andre', 'Largo', 'Ghostbusters'),('Rigby', 'Oates', 'Back To The Future'),('Benjamin', 'Button', 'Velocipastor'),('Valerie', 'Maddison', 'Zombieland'),
('Jeff', 'Goldblum', 'Jurassic Park'),('Ash', 'Ketchum', 'Pokemon The First Movie'),('Robert', 'Buccanan', 'Sharknado'),('Sheldon', 'Cooper', 'Terminator'),('Sirius', 'Black', 'Cujo'),('Peggy', 'Hill', 'Godzilla 2000'),('Carson', 'Baxter', 'Cujo'),('Patrick', 'Simmons', 'Jurassic World'),('Mariah', 'Carey', 'The Descent'),('Mark', 'Hamill', 'Jurassic Park'),
('Sam', 'Neil', 'PS I Love You'),('Derick', 'Manor', 'Pacific Rim'),('Patricia', 'Star', 'Sharknado'),('Leonard', 'Nemoy', 'Dogma'),('Patrick', 'Lupin', 'Cujo'),('Jack', 'Harken', 'Hitman'),('Carlton', 'Smith', 'Carrie'),('Timothy', 'Curry', 'King Kong'),('Meagan', 'Griffin', 'Fried Green Tomatoes'),('Skye', 'Jones', 'Die Hard'),
('Edward', 'Sheeran', 'Iron Man'),('Robert', 'Madison', 'Twilight'),('Bucky', 'Burnham', 'Black Panther'),('Zachary', 'Hines', 'Dogma'),('Barbara', 'Hewitt', 'About Time'),('Nathan', 'Brown', 'The Punisher'),('Will', 'Smith', 'Independance Day'),('Jessie', 'Eisenburg', 'Now You See Me'),('Stewart', 'Mason', 'Rocky Horror Picture Show'),('Henry', 'Haskins', 'Mad Max'),
('Suzie', 'Queue', 'Club Dredd'),('Happy', 'Johnson', 'Iron Man'),('Joeseph', 'Jostar', 'Jurassic Park'),('Richard', 'Simmons', 'Love Actually'),('Jeff', 'Epstein', '300'),('Jessica', 'Peterson', 'Hitman'),('Addison', 'White', 'Hitch'),('Walter', 'Witt', 'Catch Me If You Can'),('Mason', 'Brown', 'Tommy Boy'),('Bruce', 'Gilbert', 'Waterworld'),
('Brock', 'Sampson', 'Spiderman'),('Tony', 'Stark', 'Taxi'),('Emily', 'Blunt', 'Zoolander'),('Yondu', 'Star', 'Taxi'),('Ruth', 'Goldburg', 'Die Hard'),('Maggie', 'Simpson', 'The Hulk'),('Walter', 'Reed', 'The Longest Yard'),('Janice', 'Simmons', 'Castaway'),('Rick', 'Sanchez', 'Tommy Boy'),('Barry', 'DeWitt', '28 Days Later'),
('Jonathan', 'Venture', 'Dr Strange'),('Robert', 'Hill', 'About Time'),('James', 'Gunn', 'The Descent'),('Eric', 'Pearson', 'Zoolander'),('Asia', 'Simmons', '300'),('Peter', 'Griffin', 'The Godfather'),('Scott', 'Reed', 'The Green Mile'),('Stacy', 'Vickers', 'Milk'),('Lucas', 'Picard', 'Little Pet Shop of Horrors'),('Mary', 'Simmons', 'Cars'),
('William', 'Greene', 'King Kong'),('Wilma', 'Flintstone', 'What Dreams May Come'),('Johnny', 'Cash', 'Jailbreak'),('Norman', 'Osborne', 'Spiderman'),('Leon', 'Jones', 'Rush Hour'),('Vincnet', 'Vaughn', 'What Dreams May Come'),('Charles', 'Vickers', 'The Thing'),('Mason', 'Hughes', 'Summer of Sam'),('Baxter', 'Lucas', 'Star Wars The Phantom Menace'),('Homer', 'Simpson', 'The Lion King'),
('Hank', 'Venture', 'Godzilla 2000'),('Pepper', 'Potts', 'Home Alone'),('Bradly', 'Paisly', 'Survivor'),('Dana', 'Lawhorne', 'Pacific Rim'),('Teddy', 'Boothe', 'Rush Hour 2'),('Leroy', 'Jenkins', 'Danger Zone'),('Benson', 'Rockwell', 'Childs Play'),('Edward', 'Elric', 'The Pact'),('Patricia', 'Burham', 'Star Wars The Empire Strikes Back'),('Fred', 'Lee', 'The Land Before Time'),
('Bobby', 'Bertrum', 'Die Hard'),('Hazel', 'Knutz', 'Point Break'),('Ameila', 'Brown', 'Max Payne'),('Leo', 'Vaughn', 'The Descent'),('James', 'Picard', 'Rush Hour 3'),('Baxter', 'Jameson', 'Death of a Salesman'),('Micah', 'Beachum', 'The Ritual'),('Jake', 'Hill', 'The Ritual'),('Bingus', 'Bongus', 'Titanic'),('Jeff', 'Beechum', 'Slither'),
('James', 'Pesto', 'Jurassic Park'),('Betty', 'White', 'Lake Placid'),('Amanda', 'Smith', 'Max Payne'),('Miguel', 'Paquio', 'Avatar'),('George', 'Lucas', 'Back To the Future'),('Jonah', 'Jameson', 'Spiderman'),('Harry', 'Potter', 'Sherman and Mr Peabody'),('Stanley', 'Hill', 'Holes'),('Harriett', 'Baker', 'John Tucker Must Die'),('Paige', 'Thomas', 'Training Day'),
('Ryan', 'Reynolds', 'Jurassic Park'),('Phillip', 'McKaren', 'Safe'),('Jacob', 'DeWitt', 'Max Payne'),('George', 'Jefferson', 'Monster'),('Robert', 'Redford', 'Back to the Future'),('Ronald', 'Day', 'Superbad'),('Gwen', 'Stacy', 'Holes'),('Gene', 'Pearlman', 'Holes'),('Henrietta', 'Lewis', 'Donnie Darko'),('Hannah', 'Thompson', 'The Loser'),
('William', 'Turner', 'Taxi'),('James', 'Barnes', 'Black Panther'),('Hailey', 'Williams', 'Jurassic Park'),('Johnny', 'Bravo', 'Little Women'),('Bruce', 'Yelnats', 'Holes'),('Donald', 'Day', 'Howard The Duck'),('Katelyn', 'Potter', 'Cars'),('Grace', 'Umbridge', 'Pet Semetary'),('Cleveland', 'Brown', 'A Scanner Darkly'),('Reid', 'Richards', 'PS I Love You'),
('Gloria', 'Perkins', 'The Tigger Movie'),('Bruce', 'Davis', '28 Days Later'),('Michael', 'Myers', 'Halloween'),('Edgar', 'Manning', 'Romeo and Juliet'),('Stanley', 'Kubrick', 'Taxi'),('Margaret', 'Daye', 'Carrie'),('Charles', 'Day', 'Hostel'),('Martha', 'Kitt', 'Strangers'),('Joeseph', 'Stern', 'Butterfly Effect'),('Susan', 'Storm', 'Forrest Gump'),
('Jeffery', 'Simpson', 'Life of Pi'),('David', 'Davidson', 'Monster'),('Gabriel', 'Iglesias', 'Magic Mike'),('David', 'Mews', 'Year One'),('Stanly', 'Walters', 'Ghostbusters'),('Sonny', 'Daye', 'The Thing'),('Ruth', 'Potter', 'Critters'),('Kevin', 'Bacon', 'Critters II'),('Joey', 'Beechum', 'Cujo'),('Benjamin', 'Grimm', 'Eight Mile'),
('Mallory', 'Frank', 'Terminator'),('Diesel', 'Malone', 'Life of Pi'),('Karen', 'Rogers', 'Magic Mike'),('Jeremey', 'Irons', 'Year One'),('Greg', 'Wilko', 'Ghostbusters'),('Amanda', 'Lee', 'The Thing'),('Agnis', 'McPhee', 'Ghoulies'),('Kevin', 'Paige', 'Hitch'),('Benny', 'McPhee', 'Spiderman'),('Edward', 'Grim', 'The Green Mile'),
('Michelle', 'Galloway', 'King Kong'),('Benjamin', 'Parker', 'Life of Pi'),('Richard', 'Wilkes', 'Star Wars The Clone Wars'),('Jackie', 'Kennedy', 'Apollo 13'),('Roger', 'Smith', 'Ghostbusters'),('Josh', 'Lee', 'King Kong'),('Angus', 'McPhee', 'Ghoulies II'),('Paige', 'Smith', 'Hitchcock'),('Hannah', 'Harman', 'Birdman'),('Michael', 'McPhee', 'Independance Day'),
('Benjamin', 'Carter', 'Disturbia'),('Daisy', 'Dukes', 'Dukes of Hazard'),('Jordan', 'Keyes', 'Star Wars A New Hope'),('Nathan', 'Winters', 'Apollo 13'),('Hailey', 'Smith', 'Spawn'),('Jarred', 'Lee', 'The Punisher'),('Jamie', 'Lawhorn', 'Full Metal Jacket'),('Leigh', 'Dalton', 'American Psycho'),('Sarah', 'Harman', 'Jeepers Creepers'),('Eric', 'Andre', 'Slither'),
('Robert', 'Morales', 'Mad Max'),('Jessica', 'Jones', 'The Avengers'),('Michael', 'Keaton', 'Jurassic Park'),('Ethan', 'Winters', 'Contagion'),('Marcus', 'Smith', 'The Punisher'),('Micah', 'Carter', 'Spawn'),('Lexi', 'Faris', 'Hard Gems'),('Ronnie', 'Dalton', 'Spiderman'),('Emily', 'Harman', 'Scream'),('Jonah', 'Hill', 'Superbad');

create table Watched_Movies(movie varchar(50), user_id int);
CALL fill_table2();

UPDATE users SET firstname =  UPPER(firstname), lastname = UPPER(lastname), last_movie = UPPER(last_movie);
UPDATE watched_movies SET movie = UPPER(movie);

